export const TEST_ALERTMANAGER_URL = 'TEST_ALERTMANAGER_URL'
export const TEST_ALERTMANAGER_URL_SUCCESS = 'TEST_ALERTMANAGER_URL_SUCCESS'
export const TEST_ALERTMANAGER_URL_FAIL = 'TEST_ALERTMANAGER_URL_FAIL'


export const FETCH_ALERTS = 'FETCH_ALERTS';
export const FETCH_ALERTS_SUCCESS = 'FETCH_ALERTS_SUCCESS';
export const FETCH_ALERTS_FAIL = 'FETCH_ALERTS_FAIL';

export const TOGGLE_ALERT_SEVERITY = 'TOGGLE_ALERT_SEVERITY';
export const TOGGLE_ALERTS_STARTTIME ='TOGGLE_ALERTS_STARTTIME';
export const TOGGLE_ALERT_NAME = 'TOGGLE_ALERT_NAME'

export const FETCH_STATUS_DATA = 'FETCH_STATUS_DATA';
export const FETCH_STATUS_DATA_FAIL = 'FETCH_STATUS_DATA_FAIL';
export const FETCH_STATUS_DATA_SUCCESS = 'FETCH_STATUS_DATA_SUCCESS';

export const FETCH_RECERVER = 'FETCH_RECERVER';
export const FETCH_RECERVER_SUCCESS = 'FETCH_RECERVER_SUCCESS';
export const FETCH_RECERVER_FAIL = 'FETCH_RECERVER_FAIL';

export const CHECK_INHIBITED = 'CHECK_INHIBITED';
export const CHECK_SILENCED = 'CHECK_SILENCED';

export const CHANGE_SERCH_TERM = 'CHANGE_SERCH_TERM';
export const SELECT_RECEIVER = 'SELECT_RECEIVER';

export const ALERT_ADD_FILTER = 'ALERT_ADD_FILTRT';
export const ALERT_REMOVE_FILTER = 'ALERT_REMOVE_FILTER'

export const FETCH_SILENCES = 'FETCH_SILENCES';
export const FETCH_SILENCES_SUCCESS = 'FETCH_SILENCES_SUCCESS';
export const FETCH_SILENCES_FAIL = 'FETCH_SILENCES_FAIL';
export const SHOW_SILENCES_WITH_STATUS = 'SHOW_SILENCES_WITH_STATUS';
export const FETCH_SILENCE_WITH_ID = 'FETCH_SILENCE_WITH_ID';

export const FETCH_SILENCE_WITH_ID_SUCCESS = 'FETCH_SILENCE_WITH_ID_SUCCESS';
export const FETCH_SILENCE_WITH_ID_FAIL = 'FETCH_SILENCE_WITH_ID_FAIL';

export const FETCH_SILENCE_WITH_AFFECTED_ALERTS_SUCCESS = 'FETCH_SILENCE_WITH_AFFECTED_ALERTS_SUCCESS';

export const POST_NEW_SILENCE = 'POST_NEW_SILENCE'
export const POST_NEW_SILENCE_SUCCESS = 'POST_NEW_SILENCE_SUCCESS'
export const POST_NEW_SILENCE_FAIL = 'POST_NEW_SILENCE_FAIL'

export const DELETE_SILENCE_WITH_ID = 'DELETE_SILENCE_WITH_ID'
export const DELETE_SILENCE_WITH_ID_FAIL = 'DELETE_SILENCE_WITH_ID_FAIL';
export const DELETE_SILENCE_WITH_ID_SUCCESS = 'DELETE_SILENCE_WITH_ID_SUCCESS'

export const SAVE_URL_TO_STORAGE = 'SAVE_URL_TO_STORAGE';
export const LOAD_API_URL_FROM_STORAGE = 'LOAD_API_URL_FROM_STORAGE';