export const TEST_HELLO = 'TEST_HELLO';
export const TEST_HELLO_ASYNC = 'TEST_HELLO_ASYNC';

export const FETCH_ALERTS = 'FETCH_ALERTS';
export const FETCH_ALERTS_SUCCESS = 'FETCH_ALERTS_SUCCESS';
export const FETCH_ALERTS_FAIL = 'FETCH_ALERTS_FAIL'
