export const TEST_HELLO = 'TEST_HELLO';
export const TEST_HELLO_ASYNC = 'TEST_HELLO_ASYNC';

export const FETCH_ALERTS = 'FETCH_ALERTS';
export const FETCH_ALERTS_SUCCESS = 'FETCH_ALERTS_SUCCESS';
export const FETCH_ALERTS_FAIL = 'FETCH_ALERTS_FAIL';

export const TOGGLE_ALERT_SEVERITY = 'TOGGLE_ALERT_SEVERITY';
export const TOGGLE_ALERTS_STARTTIME ='TOGGLE_ALERTS_STARTTIME';
export const TOGGLE_ALERT_NAME = 'TOGGLE_ALERT_NAME'

export const FETCH_STATUS_DATA = 'FETCH_STATUS_DATA';
export const FETCH_STATUS_DATA_FAIL = 'FETCH_STATUS_DATA_FAIL';
export const FETCH_STATUS_DATA_SUCCESS = 'FETCH_STATUS_DATA_SUCCESS';