# The root route with all parameters, which are inherited by the child
# routes if they are not overwritten.

receivers:
- name: "webhook-critical"
  webhook_configs:
  - url: 'http://localhost:8080/webhooks/critical'
    send_resolved: true

- name: "webhook-warning"
  webhook_configs:
  - url: 'http://localhost:8080/webhooks/warning'
    send_resolved: true
route:
  receiver: 'webhook-warning'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  group_by: [cluster, alertname]

  routes:
  - receiver: 'webhook-critical'
    group_wait: 10s
    match_re:
      severity: critical
inhibit_rules:      
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname']